# Generated by Django 2.1.3 on 2018-11-21 23:01

import JobMatcherApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JobMatcherApp', '0002_employer_seeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=JobMatcherApp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='desired title')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('top_skills', JobMatcherApp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=5)),
                ('extra_skills', JobMatcherApp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('familiar_with', JobMatcherApp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('requirements', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobMatcherApp.Employer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
