# Generated by Django 2.1.3 on 2018-11-30 01:55

import JobMatcherApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatcherApp', '0004_add_profile_header_metrics'),
        ('jobs', '0001_create_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(default=JobMatcherApp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('seeker_action', models.CharField(blank=True, choices=[('SKIP', 'SKIP'), ('SUPER', 'SUPER'), ('APPLY', 'APPLY')], max_length=20)),
                ('employer_action', models.CharField(blank=True, choices=[('SKIP', 'SKIP'), ('SUPER', 'SUPER'), ('CALL', 'CALL')], max_length=20)),
                ('is_archived_seeker', models.BooleanField(default=False)),
                ('is_archived_employer', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='JobMatcherApp.Employer')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='JobMatcherApp.Employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='match',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='JobMatcherApp.Seeker'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('employer', 'seeker', 'job')},
        ),
    ]
