# Generated by Django 2.1.3 on 2018-11-28 07:32

import JobMatcherApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatcherApp', '0002_employer_seeker'),
        ('jobs', '0002_update_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(default=JobMatcherApp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('seeker_action', models.CharField(blank=True, max_length=20)),
                ('employer_action', models.CharField(blank=True, max_length=20)),
                ('is_archived_seeker', models.BooleanField(default=False)),
                ('is_archived_employer', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='JobMatcherApp.Employer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.Job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='JobMatcherApp.Seeker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('employer', 'seeker', 'job')},
        ),
    ]
