# Generated by Django 2.1.3 on 2018-11-16 12:50

import JobMatcherApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatcherApp', '0001_create_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.CharField(default=JobMatcherApp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('photo', models.URLField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='summary')),
                ('confirm_spending', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=30, verbose_name='company name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.CharField(default=JobMatcherApp.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated time')),
                ('photo', models.URLField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='summary')),
                ('confirm_spending', models.BooleanField(default=False)),
                ('desired_title', models.CharField(blank=True, max_length=150, verbose_name='desired title')),
                ('top_skills', JobMatcherApp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=5)),
                ('extra_skills', JobMatcherApp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('other_skills', JobMatcherApp.models.SkillsField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('experience', models.CharField(blank=True, max_length=500)),
                ('education', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
