# Generated by Django 2.1.3 on 2018-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatcherApp', '0002_employer_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
