# Generated by Django 2.1.3 on 2018-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobMatcherApp', '0004_add_profile_header_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='education',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='experience',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
