export const ERROR_UPDATE_PROFILE = "ERROR_UPDATE_PROFILE";
export const UPDATE_PROFILE_IMG = "UPDATE_PROFILE_IMG";
export const UPDATE_PROFILE_PASSWORD = "UPDATE_PROFILE_PASSWORD";
export const FETCHING_UPDATE_PROFILE = "FETCHING_UPDATE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const FETCHING_GET_PROFILE = "FETCHING_GET_PROFILE";
